POST http://localhost:8080/payments HTTP/1.1
content-type: application/json

{
    "amount": 100,
    "currency": "EUR",
    "method": {
        "type": "creditCard",
        "details": {
        "number": "1234123412341234",
        "expiration_date": "01/2022",
        "cvv": "123",
        "holder_name": "John Doe"
        }
    },
    "customer_id": "1234567890123456",
    "order_id": "123456"
}